### ISSUE TITLE
Drivetrain Code

### ISSUE THREAD

**Issue by OccultSlolem** [Nuts-Bolts-FRC-7528/FRC-2020#2]
Criteria:

- Single joystick arcade drive
- Prints out power levels periodically to DS
- 4 CAN Talon SRX Drivetrain
- 5% deadband

**Comment by OccultSlolem** [comment]
(@luiscarrillo310  put any further criteria down here)

**Comment by luiscarrillo310** [comment]
Finished the drive train code on January 15th, 2020.
